### ISSUE TITLE
Update to node 20

### ISSUE THREAD

**Issue by eskalera** [blombard/review-reminder#34]
It seems [update to node16](https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/#:~:text=GitHub%20Actions%3A%20All%20Actions%20will%20run%20on%20Node16%20instead%20of%20Node12,-actions&text=Node%2012%20has%20been%20out,on%20Node16%20by%20Summer%202023.) has already gone by.

Github is already recommending to update to [node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)

**Comment by blombard** [comment]
Wow nice catch 👍
